In [1]:
import numpy as np
import pandas as pd
from bic import *
from simulate_bias import *

In [2]:
np.random.seed(1)
y, X = simulate_ovb(
    nindividuals=100,
    nfeatures=2,
    ngroups=2,
    nperiods=5,
    theta=np.array([0.1,0.5]),
    alpha=alpha(5),
    low=-3,
    up=3
)

In [3]:
a =  bic(outcome=y, ngroups=2, nperiods=5, nindividuals=100, alpha_0=alpha(5),
                                                    theta_0 = np.array([0.1,0.5]), X=X, nfeatures=2)

In [4]:
a

{'Estimates': array([ 0.11590026,  0.48204788,  1.21705521,  1.15173962,  1.10112414,
         1.29141839,  1.25267666, -0.23114129, -0.34824144, -0.62974007,
        -0.85162144, -0.95388687]),
 'sd': array([0.02397042, 0.02508125, 0.10940639, 0.14124951, 0.13198043,
        0.12103953, 0.14797876, 0.12415097, 0.14268259, 0.11484082,
        0.15753641, 0.13640984]),
 'bic': 2.4871269371241977,
 'objective': 445.09829762684285}

In [6]:
b =  bic(outcome=y, ngroups=2, nperiods=5, nindividuals=100, alpha_0=np.array([ 1 ,  1.1,  1.15,  1.2,  1.3,
       -0.1       , -0.2       , -0.3       , -0.4       , -0.5        ]) ,theta_0 = np.array([0.1,0.5]), X=X, nfeatures=2)
b

{'Estimates': array([ 0.11590026,  0.48204788,  1.21705521,  1.15173962,  1.10112414,
         1.29141839,  1.25267666, -0.23114129, -0.34824144, -0.62974007,
        -0.85162144, -0.95388687]),
 'sd': array([0.02408516, 0.02509055, 0.11211073, 0.14518402, 0.12698282,
        0.12452195, 0.13984745, 0.12075894, 0.13879225, 0.12194268,
        0.152356  , 0.14586316]),
 'bic': 2.4871269371241977,
 'objective': 445.09829762684285}

In [7]:
c = bic(outcome=y, ngroups=3, nperiods=5, nindividuals=100, alpha_0=np.array([ 1 ,  1.1,  1.15,  1.2,  1.3,
       -0.1       , -0.2       , -0.3       , -0.4       , -0.5,  -0.3 , -0.5       , -0.7       , -0.9       , -1.2     ]) ,theta_0 = np.array([0.1,0.5]), X=X, nfeatures=2)

In [8]:
c

{'Estimates': array([ 0.12113601,  0.48225612,  1.21912408,  1.24209999,  1.15534619,
         1.35665194,  1.42793188,  0.20807105, -0.12737683, -0.52056166,
        -0.17214842, -0.51068282, -0.63478364, -0.57555298, -0.50495571,
        -1.67051718, -1.60400125]),
 'sd': array([0.02351066, 0.02291508, 0.11339495, 0.14045314, 0.13625178,
        0.12452737, 0.12972872, 0.16172561, 0.17902286, 0.18189623,
        0.19218496, 0.18018723, 0.17838581, 0.2077794 , 0.15840903,
        0.15789007, 0.13356737]),
 'bic': 2.309695172882623,
 'objective': 398.4352589085281}

In [9]:
b

{'Estimates': array([ 0.11590026,  0.48204788,  1.21705521,  1.15173962,  1.10112414,
         1.29141839,  1.25267666, -0.23114129, -0.34824144, -0.62974007,
        -0.85162144, -0.95388687]),
 'sd': array([0.02408516, 0.02509055, 0.11211073, 0.14518402, 0.12698282,
        0.12452195, 0.13984745, 0.12075894, 0.13879225, 0.12194268,
        0.152356  , 0.14586316]),
 'bic': 2.4871269371241977,
 'objective': 445.09829762684285}

In [15]:
pd.DataFrame(b['Estimates'])

0
0   0.115900
1   0.482048
2   1.217055
3   1.151740
4   1.101124
5   1.291418
6   1.252677
7  -0.231141
8  -0.348241
9  -0.629740
10 -0.851621
11 -0.953887

In [14]:
b['Estimates']

array([ 0.11590026,  0.48204788,  1.21705521,  1.15173962,  1.10112414,
        1.29141839,  1.25267666, -0.23114129, -0.34824144, -0.62974007,
       -0.85162144, -0.95388687])

In [16]:
b['objective']/500

0.8901965952536857

In [17]:
c['objective']/500

0.7968705178170562

In [20]:
sum((b['bic'] < c['bic'])*1).mean() # I will need to do this for all

0

In [75]:
(b['bic'] < c['bic'] )& (b['bic'] < f['bic']) & (b['bic'] < h['bic'])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

[2.4871269371241977,
 2.7329729044846287,
 2.665667127193459,
 2.557315093456678,
 2.679328979015313,
 2.715032321454252,
 2.9875820381593376,
 2.466738693550191,
 2.4855250566746707,
 2.433557581037467,
 2.603011000323636,
 2.7561837075683973,
 2.6623392997322717,
 2.670683513666142,
 2.527969908351375,
 2.7626086434605868,
 2.5859770731098157,
 2.712591117682868,
 2.752295637303585,
 2.5065781200231902,
 2.61762787481077,
 2.5240838425043517,
 2.758002391336089,
 2.771812745077595,
 2.5155043989112658,
 2.674356791530297,
 2.8983475039061406,
 2.6731910809705086,
 2.5179768917177343,
 2.7512111256646934,
 2.7287257883369795,
 2.602869520123553,
 2.564214206755914,
 2.5126474695730048,
 2.795330708540282,
 2.5435003905806655,
 2.8034579945186646,
 2.839206906953237,
 2.669147027836761,
 2.8614855233190184,
 2.5161603860442687,
 2.5553545362268846,
 2.9089063437105906,
 2.63747700067084,
 2.5427145720867323,
 2.5251427598974585,
 2.623933365046072,
 2.7560163580242674,
 2.5971052465516

In [27]:
def monte_carlo_simulation_groups(
    nindividuals,
    nfeatures,
    ngroups,
    specified_ngroups,
    nperiods,
    theta,
    alpha,
    theta_0,
    alpha_0,
    low,
    up,
    nreps,
    seed
):
    """[summary]

    Args:
        nindividuals ([type]): [description]
        nfeatures ([type]): [description]
        ngroups ([type]): [description]
        specified_ngroups([type]): [description]
        nperiods ([type]): [description]
        theta ([type]): [description]
        alpha ([type]): [description]
        theta_0
        alpha_0
        low ([type]): [description]
        up ([type]): [description]
        nreps ([type]): [description]
        seed ([type]): [description]
    
    Return:

    """
    np.random.seed(seed)
    monte_carlo_coefficients = []
    estimates_sd = []
    ic =[]
    #objective=[]
    
    for i in range(nreps):
        y, X = simulate_ovb(nindividuals, nfeatures, ngroups, nperiods, theta, alpha, low, up) 
        a = gfe_bic(outcome=y, ngroups=specified_ngroups, nperiods=nperiods, nindividuals=nindividuals, 
                                                                   alpha_0=alpha_0, theta_0 = theta_0, X=X, nfeatures=nfeatures)
        monte_carlo_coefficients.append(a['Estimates'])
        
        #variance = np.concatenate((gfe_variance(outcome=y, ngroups=specified_ngroups, nperiods=nperiods, 
        #nindividuals=nindividuals, nfeatures=nfeatures, alpha_0=alpha_0, 
        #theta_0=theta_0, X=X)))
        estimates_sd.append(a['sd'])
        ic.append(a['bic'])
        #objective.append(a['objective'])
        
    return({'Estimates': monte_carlo_coefficients, 'sd': estimates_sd}, {'bic': ic})

In [31]:
e, f = monte_carlo_simulation_groups(
    nindividuals=100,
    nfeatures=2,
    ngroups=2,
    specified_ngroups=2,
    nperiods=5,
    theta=np.array([0.1,0.5]),
    alpha=alpha(5),
    theta_0= np.array([0.1,0.5]),
    alpha_0 = alpha(5),
    low=-3,
    up=3,
    nreps=100,
    seed=1
)

# Data Frames e,f and g,h compares the Sensitivty of the Algorithm to its starting values.

In [35]:
pd.DataFrame(e['Estimates']).mean()

0     0.104036
1     0.500649
2     1.046985
3     1.100576
4     1.171096
5     1.222648
6     1.299351
7    -0.183170
8    -0.402180
9    -0.588380
10   -0.798615
11   -0.983534
dtype: float64

In [36]:
g, h = monte_carlo_simulation_groups(
    nindividuals=100,
    nfeatures=2,
    ngroups=2,
    specified_ngroups=2,
    nperiods=5,
    theta=np.array([0.1,0.5]),
    alpha=alpha(5),
    theta_0= np.array([0.1,0.5]),
    alpha_0 = np.array([ 1 ,  1.1,  1.15,  1.2,  1.3,
       -0.1       , -0.2       , -0.3       , -0.4       , -0.5        ]),
    low=-3,
    up=3,
    nreps=100,
    seed=1
)

In [37]:
pd.DataFrame(g['Estimates']).mean()

0     0.104709
1     0.500796
2     1.051247
3     1.106740
4     1.178916
5     1.229588
6     1.311194
7    -0.177195
8    -0.395005
9    -0.580788
10   -0.788911
11   -0.975394
dtype: float64

In [53]:
((pd.DataFrame(h['obj']) == pd.DataFrame(f['obj']))*1).mean()

0    0.76
dtype: float64

In [65]:
((pd.DataFrame(h['bic']) < (pd.DataFrame(f['bic']) & pd.DataFrame(b['bic'])& pd.DataFrame(c['bic'])))*1).mean()

ValueError: DataFrame constructor not properly called!

In [63]:
pd.DataFrame(f['obj']).head()

0
0  445.098298
1  489.095096
2  477.049998
3  457.753500
4  479.324667

In [62]:
pd.DataFrame(h['obj']).head(5)

0
0  445.098298
1  489.095096
2  477.049998
3  457.659228
4  479.494934

In [60]:
pd.DataFrame(e['Estimates']).head(5).round(4)*100

0      1       2       3       4       5       6      7      8      9   \
0  11.59  48.20  121.71  115.17  110.11  129.14  125.27 -23.11 -34.82 -62.97   
1  11.89  54.20   87.53  110.02   99.88  131.30  161.23 -27.09 -50.08 -64.13   
2   8.69  50.72   91.44   86.82   92.12  111.66  130.84 -24.30 -17.92 -77.47   
3   3.87  49.85  122.35  132.07  114.43  132.49  154.60 -35.65 -29.93 -55.79   
4   8.18  52.55   78.41  114.29  112.76  121.13  128.13  -8.62 -31.06 -72.91   

      10      11  
0 -85.16  -95.39  
1 -83.17 -111.29  
2 -84.60 -100.03  
3 -70.77  -99.92  
4 -83.66  -98.49

In [59]:
pd.DataFrame(g['Estimates']).head(5).round(4)*100 

0      1       2       3       4       5       6      7      8      9   \
0  11.59  48.20  121.71  115.17  110.11  129.14  125.27 -23.11 -34.82 -62.97   
1  11.89  54.20   87.53  110.02   99.88  131.30  161.23 -27.09 -50.08 -64.13   
2   8.69  50.72   91.44   86.82   92.12  111.66  130.84 -24.30 -17.92 -77.47   
3   4.00  49.88  119.92  136.41  116.85  135.18  156.84 -30.47 -30.83 -54.80   
4   8.11  52.63   80.91  113.91  114.46  126.28  128.00  -9.34 -27.75 -70.91   

      10      11  
0 -85.16  -95.39  
1 -83.17 -111.29  
2 -84.60 -100.03  
3 -69.40  -97.17  
4 -84.71  -93.90

In [61]:
alpha(5)*100

array([ 105.12710964,  110.51709181,  116.18342427,  122.14027582,
        128.40254167,  -20.        ,  -40.        ,  -60.        ,
        -80.        , -100.        ])

In [77]:
d = {'bic':[0,1,2]}
i = {'bic':[1,2,3]}
d['bic'] < i['bic']

True

In [91]:
(((pd.DataFrame(d) < pd.DataFrame(i))&(pd.DataFrame(d) < pd.DataFrame(j)))*1).mean()

bic    0.666667
dtype: float64

In [90]:
j = {'bic':[-1,2,3]}

In [94]:
estimates22, bic22 =  monte_carlo_simulation_groups (**params, nindividuals=100, nperiods=10,
alpha=alpha(10), alpha_0=np.append(np.append((alpha(10)[:10]+0.5),(alpha(10)[:10]-0.5)), np.append((alpha(10)[10:]+0.5),(alpha(10)[10:]-0.5))),
 specified_ngroups=4)

In [93]:
def compare_bic(a,b,c,d, G, T, N):
    return pd.DataFrame({
        'Selection rate': (((pd.DataFrame(a) < pd.DataFrame(b)) & (pd.DataFrame(a) < pd.DataFrame(c)) & (pd.DataFrame(a) < pd.DataFrame(d)))*1).mean(),
        'T':T,
        'N': N,
        'G': G
    })
    


"""DGP"""


params = {"nfeatures" : 2,
          "ngroups" : 2,
          "theta" : np.array([0.1, 0.5]),
          "theta_0" : np.array([0.2, 0.4]),
          "low" : -3,
          "up" : 3,
          "nreps" : 1000,
          "seed" : 1}

In [95]:
estimates1, bic1 =  monte_carlo_simulation_groups(**params, nindividuals=100, nperiods=5,alpha=alpha(5), alpha_0=(alpha(5)[:5] + alpha(5)[5:10])/2,specified_ngroups=1)

In [96]:
estimates28, bic28 =  monte_carlo_simulation_groups(**params, nindividuals=100, nperiods=5,alpha=alpha(5), alpha_0=alpha(5),specified_ngroups=2)

In [97]:
estimates10, bic10 =  monte_carlo_simulation_groups(**params, nindividuals=100, nperiods=5,
alpha=alpha(5), alpha_0=np.append(alpha(5),((alpha(5)[:5] + alpha(5)[5:10])/2)),specified_ngroups=3)

In [115]:
bic_table = pd.concat([compare_bic(bic1['bic'],bic10['bic'], bic28['bic'], bic22['bic'], N=100, T=5, G=1),
compare_bic(bic10['bic'], bic28['bic'], bic22['bic'],bic1['bic'], N=100, T=5, G=3),
compare_bic(bic22['bic'],bic1['bic'],bic10['bic'], bic28['bic'], N=100, T=5, G=4),
compare_bic(bic28['bic'],bic10['bic'],bic22['bic'],bic1['bic'], N=100, T=5, G=2)]).set_index(['T', 'N', 'G']).sort_index() #.to_latex('bic_groups.tex')

In [116]:
bic_table

Selection rate
T N   G                
5 100 1             0.0
      2             0.0
      3             0.0
      4             1.0

In [101]:
compare_bic(bic1,bic10, bic28, bic22, N=100, T=5, G=1)

Selection rate  T    N  G
bic             0.0  5  100  1
obj             0.0  5  100  1

In [102]:
compare_bic(bic10, bic28, bic28,bic1, N=100, T=5, G=3)

Selection rate  T    N  G
bic             1.0  5  100  3
obj             1.0  5  100  3

In [103]:
compare_bic(bic22,bic1,bic10,bic28, N=100, T=5, G=4)

Selection rate  T    N  G
bic             1.0  5  100  4
obj             0.0  5  100  4

In [107]:
pd.DataFrame(bic22['bic']).head()

0
0  1.831838
1  1.919508
2  1.819581
3  1.655281
4  1.805956

In [108]:
pd.DataFrame(bic10['bic']).head()

0
0  2.356378
1  2.694292
2  2.510333
3  2.466467
4  2.508776

In [110]:
 (((pd.DataFrame(bic10['bic']) < pd.DataFrame(bic1['bic'])) & (pd.DataFrame(bic10['bic']) < pd.DataFrame(bic22['bic'])) & (pd.DataFrame(bic10['bic']) < pd.DataFrame(bic22['bic'])))*1).mean()

0    0.0
dtype: float64

In [114]:
pd.DataFrame(bic10['bic']) < pd.DataFrame(bic22['bic'])

0
0    False
1    False
2    False
3    False
4    False
..     ...
995  False
996  False
997  False
998  False
999  False

[1000 rows x 1 columns]

In [118]:
from plots_groups import *

In [119]:
colors = ['#547482','#C87259','#C2D8C2','#F1B05D','#818662','#6C4A4D','#7A8C87','#EE8445','#C8B05C','#3C2030','#C89D64','#2A3B49']

In [120]:
sampling_plot(realizations=pd.DataFrame(estimates22['Estimates'])[:,2], parameters= [0.1, 0.5], colors=colors, nfeatures=2, titles=['theta one','theta two'], fig_width=9, fig_height=27, bins=30, alpha=0.8)

KeyError: (slice(None, None, None), 2)

In [ ]:
num_plots = len(realizations.columns)
    fig, ax = plt.subplots(int(num_plots/nfeatures), nfeatures, figsize=(fig_width, fig_height))
    for k in range(nfeatures):
        for i in range(int(num_plots/nfeatures)):
            sns.set_palette(colors)
            sns.histplot(
            data=realizations.iloc[:,(i+(k*int(num_plots/nfeatures)))],
            bins=bins,
            alpha=alpha,
            kde=True,
            ax=ax[i,k]
            )
            ax[i,k].axhline(0, color="black", alpha=alpha)
            ax[:,k].set_title(titles[k])
            ax[i,k].spines["right"].set_visible(False)
            ax[i,k].spines["top"].set_visible(False)
            ax[i,k].spines["top"].set_visible(False)
            #ax[i,k].vlines(parameters)
            ax[i,k].axvline(parameters[(i+(k*(int(num_plots/nfeatures))))], c=colors[1])